language: java
addons:
  sonarcloud:
    organization: "gerardryan1989-github" #the key of the org you chose at step #3
script:
  - mvn sonar-scanner

notifications:
  slack: gerardryan1989:gXhuvWuovHTZOAjSLsTxbAjT
  email:
    - gerard.ryan@students.ittralee.ie