language: java

script:
  mvn sonar:sonar \
  -Dsonar.projectKey=GerardRyan1989_DevopsCA \
  -Dsonar.organization=gerardryan1989-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=172b346e6408246f9b7b579f092f5c33253eca06
notifications:
  #slack: gerardryan1989:kLHS9sSX8OryWYXE4YpTajfD