language: java
addons:
  sonarcloud:
    organization: "gerardryan1989-github" #the key of the org you chose at step #3
    token:
      secure: "46116e7b35f48f77e3bf42c3835860efa693e487"
script:
  - sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false
notifications:
  slack: gerardryan1989:gXhuvWuovHTZOAjSLsTxbAjT
  email:
    recipients:
    - gerard.ryan@students.ittralee.ie
    on_success: always # default: change
    on_failure: always