language: java
addons:
  sonarcloud:
    organization: "gerardryan1989-github" #the key of the org you chose at step #3
script:
  - mvn sonar:sonar
notifications:
  slack: gerardryan1989:gXhuvWuovHTZOAjSLsTxbAjT
  email:
    recipients:
    - gerard.ryan@students.ittralee.ie
    - other@example.com
    on_success: always # default: change
    on_failure: always